import { Property, Broker, AboutUsConfig } from './types';

export const BROKERS: Broker[] = [
  {
    id: 'ricardo-fontes',
    name: 'Ricardo Fontes',
    title: 'Especialista em Mansões Jardins',
    phone: '+55 (99) 99123-4567',
    email: 'ricardo.fontes@faimoveis.com.br',
    creci: 'SP-123456-F',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0fwqCRpjXZInc600sKXFJjFd2BFtWrYnr61ZNh97QY_JX4RIf1U4l_csGQxg6cWisW6eh0Di4GX2FHlYlVAFJ9ZRoMtlCazwmPM9f7Ccg-l6bKlm0hQgw_OnYi5UisDd_cUNs9nuTvVInbpUDTptirt11hCtbPkLbvKuTKGQ_iASa9O1kEbIqOoUk9FDfcg_hRbHZkjqFwBoWPFmGidDlAPLzYk_1KH2fyEe4RwCAlURYO3rfLcenRa0fVYp9fL-PXBNAnkSBZA',
    rating: 4.9,
    yearsOfExperience: 15,
    propertiesSold: 200,
    bio: 'Com mais de 15 anos dedicados exclusivamente ao mercado de luxo de São Paulo, Ricardo Fontes consolidou sua reputação como o consultor de confiança para as propriedades mais icônicas dos Jardins. Sua formação em Arquitetura e Urbanismo pela FAU-USP permite uma leitura técnica profunda de cada imóvel, avaliando não apenas o valor de mercado, mas o potencial estrutural e estético de cada residência.\n\nSeu atendimento é pautado pela discrição absoluta e por um serviço de concierge imobiliário personalizado. Ricardo entende que a aquisição de uma mansão vai além da transação financeira; é a curadoria de um estilo de vida. Ele auxilia seus clientes desde a análise predial inicial até a recomendação de especialistas em design de interiores e gestão de ativos.',
    specialty: 'Jardins Expert',
    instagram: 'ricardofontes.luxury',
    linkedin: 'ricardo-fontes-realestate',
    quote: 'Exclusividade é saber que cada detalhe importa.'
  },
  {
    id: 'helena-almeida',
    name: 'Helena Almeida',
    title: 'Especialista em Lançamentos de Luxo',
    phone: '+55 (99) 99123-4568',
    email: 'helena.almeida@faimoveis.com.br',
    creci: 'SP-234567-F',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGzuV18loojQPwPEK8KnLH9ew170xhZwBZUh1hoFcT-U9IkS57iD395_1fEwtF19KK7xz_SMQ_b-tb6PcouQvAoNrdva86SNwdnVNnY9W00sp_KvaoGLCvfi2wcVLY07Vv3_YR681U5VUGmNxZ8qTX1XeilaniZtsWTE18xGVQJ-5NApD_AJX6-Prsofyp6mW3kYiEOe8Q2WwbZnmstnHxIoj4NZ_ghbfUNeeXkPzCn2Rq51pYjEPCqIijIbrnPBI5-OCZ5B1BRw',
    rating: 4.8,
    yearsOfExperience: 10,
    propertiesSold: 120,
    bio: 'Helena Almeida é especialista em novos empreendimentos residenciais de luxo em São Paulo. Ela mantém conexões próximas com as construtoras mais renomadas e possui acesso antecipado às coberturas e lofts mais exclusivos antes mesmo de chegarem ao mercado público.',
    specialty: 'Lançamentos de Luxo',
    instagram: 'helena.almeida.re',
    linkedin: 'helena-almeida-luxury',
    quote: 'Sua casa ideal é desenhada pelos seus sonhos.'
  },
  {
    id: 'marcos-veras',
    name: 'Marcos Veras',
    title: 'Especialista em Casas em Condomínio',
    phone: '+55 (99) 99123-4569',
    email: 'marcos.veras@faimoveis.com.br',
    creci: 'SP-345678-F',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgTPZabq2i69atsQ8nZSjL9_lrvOCdryzBytg6Tgzse_DaSxRX6mKY5_Cww-FretymGNOEjsNasu4GJ-ObriH5AvmE66E2pQDW6Bfe4-LDgd95fvuAxVD1r_xzNwuUIEE9g48RfNxYO3riIr989rD2hIzynfN8K5fB4YSnZiy4hx-1034irzttJWo5eDXhc17jgumODST8tDSyWGz9eaWQzevjAU1rbm7sIQibQVKXlqvWfjdeP7u7eCIxE3-4FY8VP02ThfFUhw',
    rating: 4.9,
    yearsOfExperience: 18,
    propertiesSold: 250,
    bio: 'Marcos Veras é especialista em condomínios horizontais fechados de altíssimo luxo na região metropolitana de São Paulo. Seus clientes valorizam seu profundo conhecimento sobre segurança, privacidade e infraestrutura esportiva de alto nível.',
    specialty: 'Casas em Condomínio',
    instagram: 'marcos.veras.luxury',
    linkedin: 'marcos-veras-broker',
    quote: 'Privacidade e segurança são as bases da verdadeira paz.'
  },
  {
    id: 'beatriz-luz',
    name: 'Beatriz Luz',
    title: 'Consultora de Investimentos Internacionais',
    phone: '+55 (99) 99123-4570',
    email: 'beatriz.luz@faimoveis.com.br',
    creci: 'SP-456789-F',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBpLVlcTkS-dGQXU3T0-vBY94XQG5ow3nll0HaXBBAYFdrHapCMHWWO44r1I5nAksNN-KmvZKjFwxReEIdcZus_GuOq7vXvlv6KKkw5DvRlsWEjYRmaPDWeX0f3kPNUJoRUmKVTygnVHxZItbXcpNbvH2cleQQov37yo2F6CF0OqaZfrmv_SXjWPQhRbqGqyBgB5-Dfq5TDhMzsTbXudqnDT4TcAxlBwdxIVPgZIQCaIJnpMOaDY1dQKcPlc96YcSGdM68oUZTDlA',
    rating: 4.7,
    yearsOfExperience: 8,
    propertiesSold: 85,
    bio: 'Beatriz Luz assessora compradores nacionais e internacionais na aquisição de ativos imobiliários premium em São Paulo, Miami e Nova York. Fluente em quatro idiomas, ela garante transações seguras com assessoria jurídica e cambial sob medida.',
    specialty: 'Investimentos Internacionais',
    instagram: 'beatrizluz.investment',
    linkedin: 'beatriz-luz-consultant',
    quote: 'O patrimônio mais valioso é aquele que atravessa gerações.'
  }
];

export const PROPERTIES: Property[] = [
  {
    id: 'casa-modernista-jardins',
    title: 'Casa Modernista Jardins',
    description: 'Um refúgio de design e tranquilidade no coração pulsante de São Paulo.',
    fullDescription: 'Uma verdadeira obra-prima da arquitetura contemporânea no coração dos Jardins. Esta residência exclusiva combina o uso audacioso de concreto aparente, vidro e madeira nobre, criando um diálogo constante entre o interior e o paisagismo exuberante que circunda a propriedade.\n\nCom acabamentos de altíssimo padrão, incluindo mármore travertino navona e automação residencial completa, a Casa Modernista oferece uma experiência de vida inigualável. O projeto prioriza a iluminação natural através de claraboias estratégicas e grandes vãos livres.\n\nO bairro dos Jardins é o epítome do luxo em São Paulo, oferecendo segurança, as melhores boutiques da Oscar Freire e uma gastronomia de classe mundial a poucos passos de distância.',
    type: 'Casa de Luxo',
    location: 'Jardins, SP',
    neighborhood: 'Jardins',
    price: 18500000,
    suites: 4,
    bathrooms: 6,
    area: 850,
    vagas: 6,
    condominio: 5500,
    iptu: 2200,
    images: [
      'https://lh3.googleusercontent.com/aida/AP1WRLsOlasQBGT2f4Pe6t_EbOsVduJDbuRzNJhsk40gSDq2uXaIDzn1lMeC2jzrwT0SvtERmPeBj6eAaww1vGFyv2fPyIV2navHIc8g3GxVyzsTvGo6kfWB8Uz9qrKOPyy1Vk27tu8j32eJ7n886n0nSrVHoTlotiootNEB8qGt8s73ZU5m1ugtea6dBovsYTF6shQ91afkIgxkFeMyEEHfKbD8BAnyzTPli8gn5Tbsn65xZle47rAKN9l5ZQ',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD-DkcN-pSI03YaLYgdgnxoZiZOWYQd3U3VTuT5_3Ko0yf3DGkj5cwe892phqK6JvkbT29CsyYQhF1a20cCDuKjbp8uKRrK-AKL7ijA59uvTe6jyL48wqUfjv0MI1d5TjsBZHyyB9Z3GI-eykAu4poax_w4VpgjI4ncKFkPeKozXK5i9AuQGv3y32pfVw2WOfcWtpTku_YuRyKpjmc1jF3QqWQQnMzm0kjRBpYndPoY7SBJHunp0SQqu7u5kkD_NsxC3jGxvzaICA',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDJHAsmwHKJEkU5V5-a28v7yeUUcuia-_Y_bOHQy8obXO06YqSDXGWlD_1041jE4qvIBsAsFxDR4B2YTQuMOK2SPrlRr8P3aLCasNP_TnztWiNVi4O3t_g5i1VWHRO8o7-rYknBzACSGyi_J1McNuFZdh39ecBuKNzo2oeTHSHrKJSgndrzvmDu_DZWOPb1b6azkRi9BRD-ezml46Rtc7dj0oe2o5Am2a5kROLQU0vu0_pyE71K8h6sRjyaRX0D818jYBTqvl91Yg'
    ],
    badge: 'Novo',
    comodidades: ['Piscina', 'Academia', 'Espaço Gourmet', 'Automação', 'Lareira', 'Adega'],
    brokerId: 'ricardo-fontes',
    closestPlaces: [
      { name: 'Clube Paulistano', time: '5 min' },
      { name: 'Rua Oscar Freire', time: '8 min' },
      { name: 'Parque Ibirapuera', time: '12 min' }
    ]
  },
  {
    id: 'penthouse-itaim-bibi',
    title: 'Penthouse Itaim Bibi',
    description: 'Vista panorâmica 360º em um dos endereços mais prestigiados da capital.',
    fullDescription: 'Incrível cobertura duplex no Itaim Bibi com acabamentos importados de altíssimo padrão. Com um terraço cinematográfico dotado de piscina de borda infinita privativa, esta cobertura oferece uma vista incomparável de 360 graus do skyline paulistano.\n\nAmplo living com pé-direito duplo, integração perfeita dos ambientes sociais, suítes super espaçosas com closets senhor e senhora e banhos revestidos em mármore. Uma propriedade projetada para quem valoriza a sofisticação urbana absoluta.',
    type: 'Cobertura',
    location: 'Itaim Bibi, SP',
    neighborhood: 'Itaim Bibi',
    price: 12900000,
    suites: 3,
    bathrooms: 5,
    area: 420,
    vagas: 4,
    condominio: 3800,
    iptu: 1500,
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDNHIWR9yI-SY08saz9xN-vgyQFyqPFa9aVgwGYnuMc2GbeBfzE7UcdbWUvHsc38XcdmSQI5MF1-WaxpFlhfbpjyJ3nbzP4tib7cLtp1ElDNV-5REDzRlk8dwql2PBuxqlFOBsPIp6PpX1OoUoRlAGpOKHlINiFTcRZf8BRfHQLlYglsmD15qpSp5uQjpK1EtUjMljHtCaEguqny59tmuYBHJNjltaxLYSeCjTVVFlPimSMp8PfMY2wrUUcJRFPl9JOnXWjdCufYg'
    ],
    badge: 'Exclusivo',
    comodidades: ['Piscina Infinita', 'Terraço Gourmet', 'Automação', 'Spa Privativo', 'Sala de Cinema', 'Portaria Blindada'],
    brokerId: 'helena-almeida',
    closestPlaces: [
      { name: 'Parque do Povo', time: '4 min' },
      { name: 'Shopping JK Iguatemi', time: '6 min' },
      { name: 'Faria Lima', time: '2 min' }
    ]
  },
  {
    id: 'vila-suspensa-vila-nova',
    title: 'Vila Suspensa Vila Nova',
    description: 'Arquitetura biofílica que integra a natureza ao conforto urbano absoluto.',
    fullDescription: 'Uma fantástica residência de altíssimo luxo na Vila Nova Conceição. Projeto desenvolvido pelo renomado escritório de arquitetura internacional que valoriza o bem-estar e o design biofílico.\n\nA propriedade é envolta por um exuberante jardim vertical e conta com generosos decks de madeira nobre e uma piscina integrada que criam uma atmosfera de tranquilidade absoluta, a poucos passos do Parque do Ibirapuera.',
    type: 'Apartamento Garden',
    location: 'Vila Nova Conceição, SP',
    neighborhood: 'Vila Nova Conceição',
    price: 0,
    isSobConsulta: true,
    suites: 5,
    bathrooms: 7,
    area: 1200,
    vagas: 8,
    condominio: 8000,
    iptu: 3500,
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCaZPo0J6UQ3JupYIaO2lwmK5jjE-Cu7dFBcWjubvAklKyIttIkK0QvV3vhLInLKsWKT6sM9thaD8VLTCnNnfmRZqby82vMJaj7dOuZnED5cv2XMucd2OcUM1WfpbS9ZWIxMlmmEU42gT0S8xBPFKXlCgylyAL1ALcnKx0UXNwdQAvDo1x11CbMlnHoB3ztUbup3w_9DGXNFSOu92iMhE0-j2W3AUF67nWTg07VfWMRTeT2Mln6nB9QC0ysv_W52ylf6MS5BPNjVg'
    ],
    comodidades: ['Piscina de Pedra Vulcânica', 'Jardim Privativo', 'Adega Climatizada', 'Gerador Total', 'Academia Privada', 'Guarita Blindada'],
    brokerId: 'ricardo-fontes',
    closestPlaces: [
      { name: 'Parque Ibirapuera', time: '3 min' },
      { name: 'Praça Nova Louvada', time: '5 min' },
      { name: 'Restaurante Kinoshita', time: '4 min' }
    ]
  },
  {
    id: 'apartamento-high-end-loft',
    title: 'Apartamento High-End Loft',
    description: 'Com design moderno com linhas suaves e amplas varandas envidraçadas no coração da Vila Nova.',
    fullDescription: 'Um loft exclusivo e cinematográfico com linhas suaves e amplas varandas envidraçadas no coração da Vila Nova Conceição. Com pé-direito duplo de 6 metros, acabamento contemporâneo e vista exuberante de copas de árvores em um condomínio com altíssima segurança.',
    type: 'Apartamento',
    location: 'Vila Nova Conceição, SP',
    neighborhood: 'Vila Nova Conceição',
    price: 12000000,
    suites: 2,
    bathrooms: 3,
    area: 420,
    vagas: 3,
    condominio: 2900,
    iptu: 1100,
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDdKiRy9BjCiBCyp_sDGEWAI2Gz1zhIWieH8GB7zSyN2lqfGPZ1RMuUVLahUpmDqD7Yc8MreZPk10jmeGRI-7Mr4Ub1Kiw74_WEvDAGLfpzLEljLDm-FYQzNbFPN_-ggUDZ1vxHPVAZKUSQTuw9rdmTM3U2T8dZWovL1goPk5PVkPs67iJtdS3GOSwVBq6YyAI2GceSwQ5GNFufYwaxQ4696H2ZzekMzREUiP2NHcLhzmNb3OR6YpwVAiL5bwkw2VVnyxsEbK0dVQ'
    ],
    badge: 'Exclusivo',
    comodidades: ['Pé-Direito Duplo', 'Varanda Envidraçada', 'Automação', 'Piscina Raia', 'SPA'],
    brokerId: 'helena-almeida',
    closestPlaces: [
      { name: 'Parque Ibirapuera', time: '5 min' },
      { name: 'Praça Pereira Coutinho', time: '2 min' }
    ]
  },
  {
    id: 'residencia-horizon-hill',
    title: 'Residência Horizon Hill',
    description: 'Mansão contemporânea na Cidade Jardim com projeto horizontal e piscina infinita.',
    fullDescription: 'Espetacular mansão horizontal na Cidade Jardim, concebida para integrar a paisagem ao cotidiano. Projeto em concreto, madeira e ardósia escura, com generosa área social avarandada que desemboca em uma luxuosa piscina infinita voltada para a vista das copas e do skyline.',
    type: 'Casa de Luxo',
    location: 'Cidade Jardim, SP',
    neighborhood: 'Cidade Jardim',
    price: 22500000,
    suites: 5,
    bathrooms: 7,
    area: 1100,
    vagas: 8,
    condominio: 4500,
    iptu: 3100,
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD3Os8T5SV41viEZFO6z9JgQuek7qZxzvteUVD9INCvFQ1Mw7YXdBeWXkDOFoFhJ2T5yl5WaGSscJH_554p8Qfy1eD6bOhFFTYV00IHzhyNCBIZusFCImdVMwkQJoOb6puUeZsG04j8PrfFsTi_LSsd6IjHLHiuo-e7PNlP17WVcspESvckYHauT_nqkInK5l00OsarPaaEDqDfIK3tUU-Q4IYck7GUdagmpW_8aMadSwzQh_3dSD4p-BKfEoZcuOXn_0c42gZAfw'
    ],
    badge: 'Destaque',
    comodidades: ['Piscina de Borda Infinita', 'Home Theater', 'Adega de Pedra', 'Estacionamento de Serviço', 'Guarita Blindada'],
    brokerId: 'marcos-veras',
    closestPlaces: [
      { name: 'Shopping Cidade Jardim', time: '4 min' },
      { name: 'Clube Paineiras', time: '6 min' }
    ]
  },
  {
    id: 'casa-geometria-pura',
    title: 'Casa Geometria Pura',
    description: 'Obra-prima do minimalismo arquitetônico com balanço estrutural imponente.',
    fullDescription: 'Uma residência icônica em Alto de Pinheiros. Linhas puras de concreto aparente e painéis pivotantes de madeira. O andar superior possui um vão livre flutuante fantástico, que proporciona sombra e sofisticação sobre o jardim de estilo zen com projeto de iluminação personalizado.',
    type: 'Casa de Luxo',
    location: 'Alto de Pinheiros, SP',
    neighborhood: 'Alto de Pinheiros',
    price: 15800000,
    suites: 4,
    bathrooms: 6,
    area: 680,
    vagas: 6,
    condominio: 3200,
    iptu: 1900,
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCQTpGY9lXa9DhVFxHdxOrWsKL8nSzmj24cZnF8NHZR5VQFEw-A-S8XUBttNqVc3gTdLHLGYKaeMHQ6XI6O4yHvnu99andtQhAn0c8V3_7T9NIzHAum7SLqFdBny6G2wbbUxaJWZ8tMvOMj1bbPRMrSdzx1JnrLnEYrFWdpVF4wHtkPGPsiGqtaXWFujyku1w9cFmgfEKtS5-OTjhnme9kN_gHAQJkjXGhWDgK7KaddjNYmeV5Al9uLb0iDW_Z1Qjbjc0gpIdLLRg'
    ],
    comodidades: ['Jardim Zen', 'Balanço Arquitetônico', 'Ofurô', 'Painéis Pivotantes', 'Energia Solar', 'Gerador'],
    brokerId: 'ricardo-fontes',
    closestPlaces: [
      { name: 'Parque Villa-Lobos', time: '6 min' },
      { name: 'Colégio Santa Cruz', time: '4 min' }
    ]
  }
];

export const DICTIONARY = {
  pt: {
    appName: 'FA Imóveis',
    tagline: 'A Arte de Viver Bem',
    subtitle: 'Curadoria exclusiva dos imóveis mais extraordinários nas localizações mais desejadas.',
    searchPlaceholder: 'R$ 5.000.000+',
    searchBtn: 'Explorar',
    locationLabel: 'Localização',
    typeLabel: 'Tipo',
    priceLabel: 'Preço Máximo',
    properties: 'Propriedades',
    aboutUs: 'Sobre Nós',
    concierge: 'Concierge',
    neighborhoods: 'Bairros',
    contact: 'Contato',
    exclusivity: 'Exclusividade',
    weeklyHighlights: 'Destaques da Semana',
    viewAll: 'Ver todos os imóveis',
    suites: 'Quartos',
    area: 'Área',
    vagas: 'Vagas',
    condominio: 'Condomínio',
    iptu: 'IPTU',
    detailsBtn: 'Ver Detalhes',
    sobConsulta: 'Sob Consulta',
    specialistsTitle: 'Nossos Especialistas',
    specialistsSubtitle: 'Atendimento personalizado com os maiores conhecedores do mercado de alto padrão em São Paulo.',
    whatsappBtn: 'WhatsApp',
    aboutSpecialist: 'Sobre o Especialista',
    propertiesUnderManagement: 'Imóveis Sob Gestão',
    startJourney: 'Inicie Sua Próxima Jornada',
    journeySubtitle: 'Interessado em uma das propriedades ou busca uma consultoria privada? Entre em contato diretamente para um atendimento exclusivo.',
    fullName: 'Nome Completo',
    email: 'E-mail',
    phone: 'Telefone',
    interestLabel: 'Qual o seu interesse?',
    messageLabel: 'Mensagem',
    sendBtn: 'Enviar Mensagem',
    simularParcelas: 'Simular parcelas',
    interestFinancing: 'Interessado no financiamento?',
    verifiedAgent: 'Especialista Verificado',
    aboutProperty: 'Sobre o Imóvel',
    comodidades: 'Comodidades',
    privilegedLocation: 'Localização Privilegiada',
    similarProperties: 'Propriedades Semelhantes',
    fullPortfolio: 'Ver Portfólio Completo',
    scheduleVisit: 'Agendar Visita',
    speakWithSpecialist: 'Falar com Especialista',
    allRightsReserved: 'Todos os direitos reservados.',
    yearsOfExperience: 'Anos de Mercado',
    propertiesSold: 'Imóveis Vendidos',
    averageRating: 'Avaliação Média',
    contactDirectly: 'E-mail Direto',
    creci: 'CRECI',
    successTitle: 'Mensagem Enviada!',
    successMessage: 'Obrigado por entrar em contato. Nosso especialista entrará em contato o mais rápido possível.',
    close: 'Fechar',
    favorites: 'Favoritos',
    noFavorites: 'Nenhuma propriedade favoritada ainda. Toque no ícone de coração para salvar suas favoritas.',
    myMessages: 'Minhas Mensagens',
    noMessages: 'Nenhum contato enviado ainda.',
    adminPanel: 'Painel Admin'
  },
  en: {
    appName: 'FA Imóveis',
    tagline: 'The Art of Living Well in São Paulo',
    subtitle: 'Exclusive curation of the most extraordinary properties in the most coveted locations.',
    searchPlaceholder: 'R$ 5,000,000+',
    searchBtn: 'Explore',
    locationLabel: 'Location',
    typeLabel: 'Type',
    priceLabel: 'Max Price',
    properties: 'Properties',
    aboutUs: 'About Us',
    concierge: 'Concierge',
    neighborhoods: 'Neighborhoods',
    contact: 'Contact',
    exclusivity: 'Exclusivity',
    weeklyHighlights: 'Weekly Highlights',
    viewAll: 'View all properties',
    suites: 'Bedrooms',
    area: 'Area',
    vagas: 'Parking',
    condominio: 'Condo Fee',
    iptu: 'Property Tax',
    detailsBtn: 'View Details',
    sobConsulta: 'Upon Request',
    specialistsTitle: 'Our Specialists',
    specialistsSubtitle: 'Personalized service with the leading connoisseurs of the luxury market in São Paulo.',
    whatsappBtn: 'WhatsApp',
    aboutSpecialist: 'About the Specialist',
    propertiesUnderManagement: 'Managed Properties',
    startJourney: 'Begin Your Next Journey',
    journeySubtitle: 'Interested in a property or looking for private consulting? Reach out directly for exclusive guidance.',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    interestLabel: 'What is your interest?',
    messageLabel: 'Message',
    sendBtn: 'Send Message',
    simularParcelas: 'Simulate installments',
    interestFinancing: 'Interested in financing?',
    verifiedAgent: 'Verified Specialist',
    aboutProperty: 'About the Property',
    comodidades: 'Amenities',
    privilegedLocation: 'Privileged Location',
    similarProperties: 'Similar Properties',
    fullPortfolio: 'View Full Portfolio',
    scheduleVisit: 'Schedule Visit',
    speakWithSpecialist: 'Speak with Specialist',
    allRightsReserved: 'All rights reserved.',
    yearsOfExperience: 'Years in Market',
    propertiesSold: 'Properties Sold',
    averageRating: 'Average Rating',
    contactDirectly: 'Direct Email',
    creci: 'CRECI',
    successTitle: 'Message Sent!',
    successMessage: 'Thank you for your inquiry. Our specialist will get back to you as soon as possible.',
    close: 'Close',
    favorites: 'Favorites',
    noFavorites: 'No bookmarked properties yet. Tap the heart icon to save your favorites.',
    myMessages: 'My Inquiries',
    noMessages: 'No inquiries sent yet.',
    adminPanel: 'Admin Panel'
  }
};

export const DEFAULT_ABOUT_US: AboutUsConfig = {
  heroSubtitlePt: "FA Imóveis Luxury Estate",
  heroSubtitleEn: "FA Imóveis Luxury Estate",
  heroTitlePt: "Nossa História & Valores",
  heroTitleEn: "Our Story & Values",
  heroDescriptionPt: "Excelência, discrição absoluta e curadoria especializada no mercado de alto padrão de Caxias, MA.",
  heroDescriptionEn: "Excellence, absolute discretion, and specialized curation in the high-end market of Caxias, MA.",
  
  officeImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBGzuV18loojQPwPEK8KnLH9ew170xhZwBZUh1hoFcT-U9IkS57iD395_1fEwtF19KK7xz_SMQ_b-tb6PcouQvAoNrdva86SNwdnVNnY9W00sp_KvaoGLCvfi2wcVLY07Vv3_YR681U5VUGmNxZ8qTX1XeilaniZtsWTE18xGVQJ-5NApD_AJX6-Prsofyp6mW3kYiEOe8Q2WwbZnmstnHxIoj4NZ_ghbfUNeeXkPzCn2Rq51pYjEPCqIijIbrnPBI5-OCZ5B1BRw",
  officeImageBadgePt: "Sede Própria",
  officeImageBadgeEn: "Headquarters",
  officeAddress: "Rua São Pedro, 263 Centro",
  
  stat1Value: "100%",
  stat1LabelPt: "Atendimento Exclusivo",
  stat1LabelEn: "Exclusive Service",
  stat2Value: "R$ 50M+",
  stat2LabelPt: "Ativos sob Curadoria",
  stat2LabelEn: "Curated Assets",
  
  contentTitlePt: "A Arte de Unir Histórias e Lares Extraordinários",
  contentTitleEn: "The Art of Uniting Stories and Extraordinary Homes",
  
  contentParagraphsPt: "A FA Imóveis nasceu do desejo profundo de preencher uma lacuna essencial no mercado imobiliário do Maranhão: um atendimento focado na altíssima exclusividade, sofisticação e segurança patrimonial. Acreditamos que a busca por uma nova residência não se resume a um processo de compra e venda; trata-se da materialização de conquistas pessoais e da criação de um legado familiar.\n\nFundada no coração de Caxias, MA, consolidamo-nos como a imobiliária boutique de referência absoluta na intermediação e assessoria de imóveis de alto padrão. Nossa curadoria rigorosa analisa detalhadamente o potencial de cada ativo, desde a assinatura arquitetônica até a segurança jurídica de cada transação, assegurando que nossos clientes tomem decisões baseadas em solidez e transparência.\n\nNossa sede própria, localizada na Rua São Pedro, 263 - Centro, Caxias MA, foi inteiramente desenhada para proporcionar uma experiência de acolhimento sob medida, proporcionando discrição absoluta e total conforto aos nossos parceiros de negócios e clientes.",
  contentParagraphsEn: "FA Imóveis was born from a deep desire to fill an essential gap in the Maranhão real estate market: a service focused on ultra-exclusivity, sophistication, and asset protection. We believe that searching for a new residence is not just a buy-and-sell process; it is the materialization of personal achievements and the creation of a family legacy.\n\nFounded in the heart of Caxias, MA, we have established ourselves as the boutique real estate agency of absolute reference in high-end property brokerage and advisory. Our rigorous curation analyzes the potential of each asset in detail, from architectural signature to the legal safety of each transaction, ensuring our clients make decisions based on solidity and transparency.\n\nOur headquarters, located at Rua São Pedro, 263 - Centro, Caxias MA, was entirely designed to provide a tailored, welcoming experience, ensuring absolute discretion and complete comfort for our business partners and clients.",
  
  pillar1TitlePt: "Curadoria Rigorosa",
  pillar1TitleEn: "Rigorous Curation",
  pillar1DescPt: "Selecionamos criteriosamente propriedades que reúnem valor arquitetônico, localização premium e acabamentos nobres.",
  pillar1DescEn: "We carefully select properties that combine architectural value, premium location, and noble finishes.",

  pillar2TitlePt: "Discrição Absoluta",
  pillar2TitleEn: "Absolute Discretion",
  pillar2DescPt: "Garantimos sigilo integral em todas as etapas da negociação, respeitando rigorosamente a privacidade dos envolvidos.",
  pillar2DescEn: "We guarantee complete confidentiality at all stages of negotiation, strictly respecting the privacy of those involved.",

  pillar3TitlePt: "Solidez e Confiança",
  pillar3TitleEn: "Solidity & Trust",
  pillar3DescPt: "Proporcionamos suporte jurídico e assessoria completa em cada fase, transformando complexidade em segurança.",
  pillar3DescEn: "We provide legal support and complete advisory at every stage, turning complexity into safety."
};
